[pytest]
markers =
    security: marks tests as security tests
testpaths = tests
python_files = test_*.py
addopts = --alluredir=reports/allure-results --html=reports/report.html --self-contained-html
